"""ttt

Revision ID: 22b17908c6dd
Revises: 
Create Date: 2019-07-18 16:55:22.165000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b17908c6dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=250), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-an-weekly-category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-minor-category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-an-weekly-category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-minor-category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-an-weekly-component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['lin-an-weekly-category.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['lin-category.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-minor-component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['lin-minor-category.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-an-weekly-component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['win-an-weekly-category.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['win-category.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-minor-component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['win-minor-category.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-an-weekly-module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=150), nullable=True),
    sa.Column('module_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['lin-an-weekly-component.component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-minor-module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=150), nullable=True),
    sa.Column('module_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['lin-minor-component.component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=150), nullable=True),
    sa.Column('module_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['lin-component.component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-an-weekly-module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=150), nullable=True),
    sa.Column('module_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['win-an-weekly-component.component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-minor-module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=150), nullable=True),
    sa.Column('module_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['win-minor-component.component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=150), nullable=True),
    sa.Column('module_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['win-component.component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-an-weekly-tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=150), nullable=True),
    sa.Column('test_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['lin-an-weekly-module.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-minor-tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=150), nullable=True),
    sa.Column('test_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['lin-minor-module.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=150), nullable=True),
    sa.Column('test_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['lin-module.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-an-weekly-tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=150), nullable=True),
    sa.Column('test_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['win-an-weekly-module.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-minor-tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=150), nullable=True),
    sa.Column('test_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['win-minor-module.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=150), nullable=True),
    sa.Column('test_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['win-module.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-an-weekly-steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=150), nullable=False),
    sa.Column('test_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=550), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['lin-an-weekly-tests.test_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-minor-steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=150), nullable=False),
    sa.Column('test_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=550), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['lin-minor-tests.test_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lin-step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=150), nullable=False),
    sa.Column('test_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=550), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['lin-test.test_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-an-weekly-steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=150), nullable=False),
    sa.Column('test_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=550), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['win-an-weekly-tests.test_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-minor-steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=150), nullable=False),
    sa.Column('test_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=550), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['win-minor-tests.test_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('win-step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=150), nullable=False),
    sa.Column('test_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=550), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['win-test.test_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('win-step')
    op.drop_table('win-minor-steps')
    op.drop_table('win-an-weekly-steps')
    op.drop_table('lin-step')
    op.drop_table('lin-minor-steps')
    op.drop_table('lin-an-weekly-steps')
    op.drop_table('win-test')
    op.drop_table('win-minor-tests')
    op.drop_table('win-an-weekly-tests')
    op.drop_table('lin-test')
    op.drop_table('lin-minor-tests')
    op.drop_table('lin-an-weekly-tests')
    op.drop_table('win-module')
    op.drop_table('win-minor-module')
    op.drop_table('win-an-weekly-module')
    op.drop_table('lin-module')
    op.drop_table('lin-minor-module')
    op.drop_table('lin-an-weekly-module')
    op.drop_table('win-minor-component')
    op.drop_table('win-component')
    op.drop_table('win-an-weekly-component')
    op.drop_table('lin-minor-component')
    op.drop_table('lin-component')
    op.drop_table('lin-an-weekly-component')
    op.drop_table('win-minor-category')
    op.drop_table('win-category')
    op.drop_table('win-an-weekly-category')
    op.drop_table('lin-minor-category')
    op.drop_table('lin-category')
    op.drop_table('lin-an-weekly-category')
    op.drop_table('bugs')
    # ### end Alembic commands ###
