"""ddd

Revision ID: 250192d2a198
Revises: 
Create Date: 2019-10-15 12:04:51.623000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250192d2a198'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_id', sa.String(length=150), nullable=False),
    sa.Column('parent_id', sa.String(length=150), nullable=False),
    sa.Column('os', sa.String(length=150), nullable=False),
    sa.Column('branch', sa.String(length=150), nullable=False),
    sa.Column('issues', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=250), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bugs')
    op.drop_table('addictions')
    # ### end Alembic commands ###
