"""dd

Revision ID: cd0b866a6dc7
Revises: 
Create Date: 2019-06-17 20:16:48.589000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0b866a6dc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('an-weekly-module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categories', sa.String(length=150), nullable=False),
    sa.Column('components', sa.String(length=150), nullable=False),
    sa.Column('module_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('an-weekly-steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('step_id', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=550), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('bugs', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('an-weekly-tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module_id', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('bugs', sa.PickleType(), nullable=False),
    sa.Column('steps', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minor-module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categories', sa.String(length=150), nullable=False),
    sa.Column('components', sa.String(length=150), nullable=False),
    sa.Column('module_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minor-steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('step_id', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=550), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('bugs', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minor-tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module_id', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('bugs', sa.PickleType(), nullable=False),
    sa.Column('steps', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categories', sa.String(length=150), nullable=False),
    sa.Column('components', sa.String(length=150), nullable=False),
    sa.Column('module_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('step_id', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=550), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('bugs', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module_id', sa.String(length=150), nullable=False),
    sa.Column('skip', sa.Boolean(), nullable=False),
    sa.Column('bugs', sa.PickleType(), nullable=False),
    sa.Column('steps', sa.PickleType(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    op.drop_table('steps')
    op.drop_table('module')
    op.drop_table('minor-tests')
    op.drop_table('minor-steps')
    op.drop_table('minor-module')
    op.drop_table('bugs')
    op.drop_table('an-weekly-tests')
    op.drop_table('an-weekly-steps')
    op.drop_table('an-weekly-module')
    # ### end Alembic commands ###
